### ISSUE TITLE
my skype name: live:.cid.de1b0f6544bf0639

### ISSUE THREAD

**Issue by stack4world** [stack4world212/ionic-local-storage#1]
If you need to chat with me freely, you can chat with me on skype.
live:.cid.6904afe341c19260

**Comment by Guga6999** [comment]
kypeSuggested,sakaremarta,Marta Šakare,False,False,,,https://avatar.skype.com/v1/avatars/sakaremarta/public,,,,,,,Marta Šakare,,,,,,,,,sakaremarta,Scd,2020-03-18 06:48:35Z
